### ISSUE TITLE
Minimal Activity Stream should be moved to Social-Syntax-Brainstorming

### ISSUE THREAD

**Issue by tantek** [w3c-social/Social-APIs-Brainstorming#16]
This https://github.com/w3c-social/Social-APIs-Brainstorming/wiki/Minimal-Activity-Stream is really a simplified JSON alternative to AS2, and thus should be moved to Social-Syntax-Brainstorming. cc @aaronpk

**Comment by aaronpk** [comment]
Thanks! https://github.com/w3c-social/Social-APIs-Brainstorming/wiki/Social-Syntax-Brainstorming

**Comment by tantek** [comment]
LOL - I meant like:  https://github.com/w3c-social/Social-Syntax-Brainstorming/wiki/Minimal-Activity-Stream instead of inside Social-API

**Comment by aaronpk** [comment]
hah oops! 

https://github.com/w3c-social/Social-Syntax-Brainstorming/wiki/Minimal-Activity-Stream
